### PR TITLE
added sensors key to docker-compose

### PR DESCRIPTION
**Pull request by wbaccinelli**
Part of solution to https://github.com/PerfectFit-project/virtual-coach-issues/issues/357

Goes together with https://github.com/PerfectFit-project/virtual-coach-rasa/pull/93

### CODE REVIEW

**Review by raar1 — APPROVED** [review]
OK looks good. But one question: are the ansible playbooks copying that key across to stage/prod? Otherwise how is it getting there?

Also (sorry another question) does something bad happen if stage and prod both run with the same key and hitting the same endpoints? If stage goes to grab some steps data does that mean prod won't get it?

**Comment by wbaccinelli** [comment]
The .env file refers to a local key, it is copied into the containers when they are built. Or am I missing a step (very very likely)? 

The key is both registered in the dev and prod environment of RRD, and the endpoint is seleceted on the base of the `ENVIRONMENT` variable sent in our .env file. So, in dev it will use the dev environment of RRD and and likewise with the prod

**Comment by raar1** [comment]
I think the mounting that is happening in the docker-compose is assuming that the key is already present (at location  `./id_rsa_perfectfitsensor` on the server) and will be made available within the container at the (read-only) location `/app/sensorprivatekey`, so that code inside the container can access it.

The key should not be bundled into the container during building because these containers are published as public github packages, and it is trivial for anyone to recover the private key from inside the built container image.

It is therefore a good idea to add a step to the playbooks that copies that key across. I can help with this tomorrow if you like?

**Comment by wbaccinelli** [comment]
Yes, it would be great if you could help me with this

**Pull request merged**
